name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ['3.8', '3.12', '3.13']
    env:
      UV_PYTHON: ${{ matrix.py }}

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: just check-static
