name: CI

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        py: ['3.10', '3.11', '3.12', '3.13']
    env:
      UV_PYTHON: ${{ matrix.py }}

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3
      - uses: astral-sh/setup-uv@v5
      - run: uv sync
      - run: just check-static

  pypi-publish:
    runs-on: ubuntu-latest
    needs: tests
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/lazympl
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - run: uv build
      - run: uv publish
